extends:
  - airbnb-typescript
  - plugin:import/typescript
  - plugin:storybook/recommended
  - plugin:@typescript-eslint/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  sourceType: module
  project: "./packages/*/tsconfig.json"
env:
  browser: true
  node: true
  es6: true
  jest: true
plugins:
  - import
  - react
  - react-hooks
  - "@typescript-eslint"
rules:
  consistent-return: 0
  prefer-const: 0
  lines-between-class-members: 0
  react/button-has-type: 0
  react/jsx-one-expression-per-line: 0
  react/jsx-props-no-spreading: 0
  react/no-array-index-key: 0
  react-hooks/rules-of-hooks: 2
  react-hooks/exhaustive-deps: 1
  import/no-unresolved: 0
  import/extensions: 0
  import/prefer-default-export: 0
  import/no-extraneous-dependencies: 0
  "@typescript-eslint/no-explicit-any": 0
  "@typescript-eslint/explicit-function-return-type": 0
  "@typescript-eslint/no-non-null-assertion": 0
  "@typescript-eslint/indent": 0
