name: NPM Publish

on:
  push:
    branches:
      - main

  workflow_dispatch:

env:
  GH_TOKEN: ${{secrets.gh_token}}

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          scope: ${{ secrets.npm_scope }}
          registry-url: https://registry.npmjs.org/

      - name: Setup Git
        run: |
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config user.name "$GITHUB_ACTOR"

      - name: Cache Dependencies
        id: cache-node
        uses: actions/cache@v2.1.7
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os}}-node-

      - name: Install Depencies
        if: steps.cache-node.output.cache-hit != 'true'
        run: yarn install --frozen-lockfile --non-interactive --silent --prefer-offline

      - name: Build
        run: yarn build

      - name: Create Release
        run: yarn run version
        env:
          GH_TOKEN: ${{secrets.gh_token}}

      - name: Publish NPM release
        run: yarn run publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
