name: Build Docs

on:
  push:
    branches:
      - main 

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-node@v2.5.0
        with: 
          node-version: 17.0.x
          
      - name: Cache node modules
        id: cache-node
        uses: actions/cache@v2.1.7
        with: 
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-key: ${{ runner.os}}-node-
          
      - name: Install dependencies
        if: steps.cache-node.output.cache-hit != 'true'
        run: yarn install --frozen-lockfile --non-interactive --silent --prefer-offline
        
      - name: Build docs
        run: yarn build-docs
        
#       - uses: actions/upload-artifacts@v2
#         with:
#           name: docs
#           path: docs
        
      - name: Commit docs
        run: |
          git commit -am "(Github Action): updated docs"
          git push origin master
          
        
        
      
