name: Build Docs

on:
  push:
    branches:
    - main 

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@2
        with: 
          node-version: 17.x
          
      - name: Cache node modules
        id: cache node
        uses: action/cache@v2
        with: 
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-key: ${{ runner.os}}-node-
          
      - name: Install dependencies
        if: steps.cache-node.output.cache-hit != 'true;
        run: yarn --ignore-scripts --ignore-optional --pure-lockfile
        
      - name: Build docs
        run: yarn build-docs
        
      - uses: actions/upload-artifacts@v2
        with:
          name: docs
          path: docs
        
      - name: Commit docs
        run: |
          git commit -am "(Github Action): updated docs"
          git push origin master
          
        
        
      
