name: Build NPM

on:
  push:
    branches:
      - main

  workflow_dispatch:

env:
  CI: true
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0

      - name: Setup git
        run: git config user.email "$GITHUB_ACTOR@users.noreply.github.com" && git config user.name "$GITHUB_ACTOR"

      - uses: actions/setup-node@v2.5.0
        with:
          node-version: 16.x

      - name: Cache node modules
        id: cache-node
        uses: actions/cache@v2.1.7
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-key: ${{ runner.os}}-node-

      - name: Install dependencies
        if: steps.cache-node.output.cache-hit != 'true'
        run: yarn install --frozen-lockfile --non-interactive --silent --prefer-offline

      - name: Build
        run: yarn build

      - name: Publish Major
        id: publish-major
        if: startsWith(github.event.head_commit.message, 'Major')
        run: yarn publish --major

      - name: Publish Minor
        id: publish-minor
        if: startsWith(github.event.head_commit.message, 'Minor')
        run: yarn publish --minor

      - name: Publish Patch
        if: ${{ !startsWith(github.event.head_commit.message , 'Major') && !startsWith(github.event.head_commit.message, 'Minor') }}
        run: yarn publish --patch

      - name: Publish
        run: |
          git add .
          git commit -m "Publish"
          git push origin main
